/* QA consumer of the exact manifest. Demonstration data is intentionally isolated. */
const M=window.BEANSTER_ASSETS,images={},scene=document.getElementById('scene'),inspect=document.getElementById('inspect'),shelf=document.getElementById('shelf');
let records=[],serial=0,selected=null,night=false,showAnchors=true,raf=0,token=0,ritual=null,consumed=false;
const types=Object.keys(M.assets).filter(id=>id.startsWith('cup_')&&!id.includes('shadow'));
function sprite(ctx,id,x,y,scale=1){const a=M.assets[id],im=images[id];if(!a||!im)return;ctx.imageSmoothingEnabled=false;ctx.drawImage(im,x-a.pivotX*scale,y-a.pivotY*scale,a.canvas[0]*scale,a.canvas[1]*scale)}
function drawTop(ctx,id,x,y,w){const a=M.assets[id];if(!a)return;sprite(ctx,id,x+a.pivotX*w/a.canvas[0],y+a.pivotY*w/a.canvas[0],w/a.canvas[0])}
function stop(){++token;cancelAnimationFrame(raf);raf=0;ritual=null;draw();}
function play(name,paint,finish){stop();const t=token,a=M.animations[name],start=performance.now();if(matchMedia('(prefers-reduced-motion: reduce)').matches){finish?.();return}function step(now){if(t!==token)return;let f=Math.floor((now-start)*a.fps/1000);if(f>=a.frames.length){raf=0;finish?.();draw();return}paint(a.frames[f],f);raf=requestAnimationFrame(step)}raf=requestAnimationFrame(step)}
function desk(){return records.filter(r=>r.day==='today')}
function tableCupPosition(index,n){let s=M.table.slots[String(Math.min(4,n))][index];return [384+(s[0]-512)*.66,830+(s[1]-280)*.66]}
function draw(id='hamster_idle_base'){
 let c=scene.getContext('2d');c.clearRect(0,0,768,1024);drawTop(c,'scene_background',0,0,768);drawTop(c,night?'window_night':'window_day',35,140,285);drawTop(c,'lamp',350,40,125);drawTop(c,'plant',18,540,160);drawTop(c,'plant',610,530,130);drawTop(c,'chair',292,597,210);drawTop(c,'storage_empty',464,285,270);drawTop(c,'storage_empty',464,380,270);
 sprite(c,'table_back',384,830,.66);sprite(c,id,390,714,.72);
 let cups=desk().slice(0,4);cups.forEach((r,i)=>{let [x,y]=tableCupPosition(i,cups.length);sprite(c,'cup_shadow_medium',x,y+2,.4);sprite(c,r.cup,x,y,.4)});sprite(c,'table_front',384,830,.66);
 sprite(c,'entrance_normal',597,255,.63);sprite(c,'box_closed',620,952,.36);c.fillStyle='#634027';c.font='24px system-ui';c.fillText('仓鼠咖啡角',36,66);c.font='21px system-ui';c.fillStyle='#fff3d4';c.fillText('收藏室 →',550,262);c.fillStyle='#634027';if(desk().length>4)c.fillText('更多 · +'+(desk().length-4),550,881);
 document.getElementById('stats').textContent=`桌面 ${desk().length} 杯 · 展示 ${cups.length} 杯 · 收藏 ${records.length} 条独立记录`;
 drawShelf();
}
function drawShelf(){let c=shelf.getContext('2d');c.clearRect(0,0,1024,684);for(let row=0;row<2;row++){drawTop(c,'storage_empty',0,row*342,1024);records.slice(row*4,row*4+4).forEach((r,i)=>sprite(c,r.cup,M.storage.slots[i][0],row*342+M.storage.slots[i][1],.72));drawTop(c,'storage_front_mask',0,row*342,1024)}}
function inspectFrame(id){const c=inspect.getContext('2d'),a=M.assets[id];c.clearRect(0,0,768,640);sprite(c,id,384,550,1);if(a.cupAnchorX!=null){let x=384+a.cupAnchorX-a.pivotX,y=550+a.cupAnchorY-a.pivotY;if(a.cupAttached)sprite(c,'cup_latte',x,y,.48);if(showAnchors){c.strokeStyle='#50e2cc';c.lineWidth=2;c.beginPath();c.moveTo(x-18,y);c.lineTo(x+18,y);c.moveTo(x,y-18);c.lineTo(x,y+18);c.stroke();c.fillStyle='#fff';c.font='18px system-ui';c.fillText(a.cupAnchorKind+' '+a.cupAnchorX+','+a.cupAnchorY,x+22,y)}}if(showAnchors){c.strokeStyle='#f2b96e';c.beginPath();c.moveTo(30,550);c.lineTo(730,550);c.stroke()}document.getElementById('details').textContent=JSON.stringify({id,canvas:a.canvas,pivot:[a.pivotX,a.pivotY],cupAnchor:a.cupAnchorX==null?null:[a.cupAnchorX,a.cupAnchorY],phase:a.cupAnchorKind},null,2)}
function setCount(n){stop();records=Array.from({length:n},()=>({id:++serial,cup:types[(serial-1)%types.length],day:'today'}));consumed=false;draw()}
function cleanup(){if(consumed)return;const yesterday=records.filter(r=>r.day==='yesterday').map(r=>r.id);if(!yesterday.length)return;consumed=true;const row=records.find(r=>r.id===yesterday[0]);play('cleanup',(id,f)=>{draw(null);inspectFrame(id);let c=scene.getContext('2d'),a=M.assets[id],x=350+f*8,y=939,scale=.47;sprite(c,id,x,y,scale);sprite(c,'box_lid',620,952,.36);sprite(c,'box_body',620,952,.36);if(f>=4&&f<10)sprite(c,row.cup,x+(a.cupAnchorX-a.pivotX)*scale,y+(a.cupAnchorY-a.pivotY)*scale,.26);if(f===10)sprite(c,row.cup,620,906,.26);sprite(c,'box_front',620,952,.36)},()=>{document.getElementById('stats').textContent='收杯完成；记录早已保存在收藏室，今天的新杯未收走。'});ritual=yesterday}
document.getElementById('add').onclick=()=>{stop();records.push({id:++serial,cup:types[(serial-1)%types.length],day:'today'});draw()};
document.getElementById('night').onclick=()=>{night=!night;draw()};document.getElementById('skip').onclick=stop;
document.querySelectorAll('[data-count]').forEach(b=>b.onclick=()=>setCount(+b.dataset.count));
document.getElementById('collect').onclick=()=>{if(!records.some(r=>r.day==='yesterday')){records.forEach(r=>r.day='yesterday');records.push({id:++serial,cup:'cup_latte',day:'today'});consumed=false}cleanup()};
document.getElementById('play').onclick=()=>play(document.getElementById('animation').value,inspectFrame);
document.getElementById('anchors').onclick=()=>{showAnchors=!showAnchors;inspectFrame(M.animations[document.getElementById('animation').value].frames[0])};
scene.onclick=e=>{let r=scene.getBoundingClientRect(),x=(e.clientX-r.left)*768/r.width,y=(e.clientY-r.top)*1024/r.height;let found=desk().slice(0,4).find((r,i)=>{let p=tableCupPosition(i,Math.min(4,desk().length));return Math.abs(x-p[0])<50&&y<p[1]+10&&y>p[1]-95});if(found)select(found);else play('idle',id=>draw(id))};
function select(r){selected=r.id;document.getElementById('recordInfo').textContent=`记录 #${r.id} · ${r.cup} · ${r.day}（同款保持独立）`}
shelf.onclick=e=>{let b=shelf.getBoundingClientRect(),x=(e.clientX-b.left)*1024/b.width,y=(e.clientY-b.top)*684/b.height,row=Math.floor(y/342),col=M.storage.slots.findIndex(p=>Math.abs(x-p[0])<90);let r=records[row*4+col];if(col>=0&&r)select(r)};
document.getElementById('delete').onclick=()=>{stop();records=records.filter(r=>r.id!==selected);selected=null;draw()};
document.getElementById('dark').onclick=()=>document.getElementById('gallery').classList.toggle('dark');document.addEventListener('visibilitychange',()=>{if(document.hidden)stop()});
Promise.all(Object.entries(M.assets).map(([id,a])=>new Promise((resolve,reject)=>{let im=new Image;im.onload=()=>{images[id]=im;resolve()};im.onerror=()=>reject(Error(a.file));im.src=a.file}))).then(()=>{setCount(4);inspectFrame('hamster_cleanup_06');document.getElementById('gallery').innerHTML=Object.entries(M.assets).map(([id,a])=>`<div class="tile"><img loading="lazy" src="${a.file}" alt="${id}">${id}<br>${a.canvas.join(' × ')}</div>`).join('');window.assetQA={ready:true,desk,records:()=>records,play,stop,setCount,cleanup,consumed:()=>consumed};play('idle',id=>draw(id))}).catch(e=>document.getElementById('stats').textContent='素材加载失败：'+e.message);
