const assert=require('assert/strict'),path=require('path'),fs=require('fs');const {chromium}=require('C:/Users/HP/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});try{const p=await b.newPage({viewport:{width:390,height:844},hasTouch:true}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());await p.goto('file:///'+path.resolve(__dirname,'../index_v5.html').replaceAll('\\','/'));
assert.equal(await p.locator('#today.active').count(),1);assert.equal(await p.locator('#today .u-gauge,#today .u-metrics,#today [data-dashboard]').count(),0);assert.equal(await p.locator('#today .cc-seated').count(),1);assert.equal(await p.locator('#today .cc-seated').getAttribute('data-motion'),null);assert.match(await p.locator('.cc-seated').getAttribute('src'),/hamster-seated-v192/);assert.ok(await p.locator('#today .u-record-cta').isVisible());
const swipe=async(dx,dy=0)=>{await p.evaluate(({dx,dy})=>{const el=document.querySelector('.page.active'),x=dx>0?60:300,y=300;for(const [type,n] of [['touchstart',0],['touchmove',.6],['touchend',1]]){const t=new Touch({identifier:1,target:el,clientX:x+dx*n,clientY:y+dy*n});el.dispatchEvent(new TouchEvent(type,{bubbles:true,cancelable:true,touches:type==='touchend'?[]:[t],changedTouches:[t]}))}},{dx,dy});await p.waitForTimeout(450)};
await swipe(170);assert.equal(await p.locator('#dashboard.active').count(),1);assert.equal(await p.locator('#dashboard .cc-corner').count(),0);assert.ok(await p.locator('#dashboard .u-gauge').isVisible());await swipe(170);assert.equal(await p.locator('#today.active').count(),1);await swipe(-170);assert.equal(await p.locator('#dashboard.active').count(),1);await swipe(-170);assert.equal(await p.locator('#today.active').count(),1);await swipe(15,180);assert.equal(await p.locator('#today.active').count(),1);
await p.evaluate(()=>{settings.systemNotifications=false;openAdd();$('fProductName').value='新坐姿拿铁';$('fCaf').value='160';$('fPrice').value='22'});await p.evaluate(()=>saveRecord());assert.equal(await p.locator('.cc-desk-cup').count(),1);await p.evaluate(()=>UI.go('dashboard'));assert.match(await p.locator('.cc-data-numbers').innerText(),/160/);assert.match(await p.locator('.cc-data-numbers').innerText(),/剩余/);assert.match(await p.locator('#dashboard .u-metrics').innerText(),/22/);
await p.evaluate(()=>CoffeeRoom.open());assert.equal(await p.locator('#collection.active').count(),1);await swipe(170);assert.equal(await p.locator('#collection.active').count(),1);await p.locator('.cc-collection-cup').click();await p.evaluate(()=>AppNav.back());assert.equal(await p.locator('#collection.active').count(),1);await p.evaluate(()=>AppNav.back());assert.equal(await p.locator('#today.active').count(),1);
await p.evaluate(()=>Motion.gallery());const burger=p.locator('article').filter({has:p.locator('[data-motion=character_burger]')});assert.equal(await burger.getByRole('button',{name:'播放表情',exact:true}).isEnabled(),true);await burger.getByRole('button',{name:'播放表情',exact:true}).click();await p.waitForFunction(()=>document.querySelector('[data-motion=character_burger][data-playing]'));assert.equal(await p.locator('.cc-seated').getAttribute('data-motion'),null);await p.evaluate(()=>AppNav.back());
for(const style of ['cup','ring','number','bar']){await p.evaluate(style=>{settings.dashboardStyle=style;UI.go('dashboard')},style);assert.ok(await p.locator('#dashboard .cc-data-gauge').isVisible());assert.equal(await p.locator('#today .u-hero').count(),0)}
await p.evaluate(()=>{openAdd();$('fProductName').value='未保存'});await swipe(170);assert.equal(await p.locator('#addModal.show').count(),1);await p.evaluate(()=>AppNav.back());assert.equal(await p.locator('#uUnsaved').count(),1);await p.evaluate(()=>AppNav.discard());
for(const width of [320,390,480]){await p.setViewportSize({width,height:844});await p.evaluate(()=>UI.go('today'));assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.evaluate(()=>UI.go('dashboard'));assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth))}
await p.reload();assert.equal(await p.locator('#today.active').count(),1);assert.equal(await p.locator('.cc-desk-cup').count(),1);assert.deepEqual(errors,[]);console.log('PASS split home pages, seated art, bidirectional loop, separate collection, data sync, burger playback, dashboard styles, dirty forms, responsive layout and reload');
}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
