const assert=require('assert/strict'),path=require('path'),fs=require('fs');
const {chromium}=require('C:/Users/HP/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});try{
const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[],checks=[];
page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
await page.goto('file:///'+path.resolve(__dirname,'../index_v5.html').replaceAll('\\','/'));
await page.waitForFunction(()=>window.ProductionScene&&ProductionScene.images.hamster_idle_base&&ProductionScene.images.scene_room_day);
const src=fs.readFileSync(path.resolve(__dirname,'../production_scene.js'),'utf8');
assert.equal(src.includes('Math.sin(t * Math.PI * 1.15)'),false);
checks.push('idle bob offset is gone from the renderer');

assert.equal(await page.locator('.cc-scene-heading').count(),0);
assert.equal(await page.locator('.cc-corner .cc-room-sign').count(),1);
assert.equal(await page.locator('.cc-page-switch button').nth(0).innerText(),'仓鼠咖啡角');
const cornerText=await page.locator('.cc-corner').innerText();
assert.equal(cornerText.includes('仓鼠咖啡角'),false);
assert.equal(cornerText.includes('收藏室'),false);
const signStyle=await page.locator('.cc-room-sign').evaluate(el=>{const s=getComputedStyle(el);return {bg:s.backgroundColor,border:s.borderTopWidth,shadow:s.boxShadow,label:el.getAttribute('aria-label')}});
assert.equal(signStyle.bg,'rgba(0, 0, 0, 0)');
assert.equal(signStyle.border,'0px');
assert.equal(signStyle.shadow,'none');
assert.equal(signStyle.label,'打开收藏室');
const covers=await page.evaluate(()=>{
  const canvas=document.querySelector('[data-scene]'),btn=document.querySelector('.cc-room-sign');
  const cr=canvas.getBoundingClientRect(),br=btn.getBoundingClientRect(),s=ProductionScene.signRect();
  const cx=cr.left+(s.x+s.w/2)/768*cr.width,cy=cr.top+(s.y+s.h/2)/1024*cr.height;
  return br.left<=cx&&cx<=br.right&&br.top<=cy&&cy<=br.bottom&&br.width>=44&&br.height>=44;
});
assert.equal(covers,true);
checks.push('single collection entrance: canvas sign plus transparent hotspot');

const layers=await page.evaluate(()=>{
  const drawn=[];
  const ys=[];
  const orig=ProductionScene.sprite;
  const origBox=ProductionScene.spriteBox;
  ProductionScene.sprite=function(ctx,id,x,y,scale,alpha){drawn.push(id);if(String(id).startsWith('hamster_'))ys.push(y);return orig.call(this,ctx,id,x,y,scale,alpha)};
  ProductionScene.spriteBox=function(ctx,id){drawn.push(id);return origBox.call(this,ctx,id)};
  ProductionScene._bob=12;
  ProductionScene.paint();
  const idle=drawn.slice();
  const row={id:'old',type:'拿铁',productName:'拿铁'};
  const sched=CleanupMotion.schedule(BEANSTER_ASSETS,[row]);
  const c=document.querySelector('[data-scene]').getContext('2d');
  const take=elapsed=>{drawn.length=0;ProductionScene.drawCleanup(c,elapsed,[row]);return drawn.slice()};
  const look=take(0),opening=take(sched.openingAt+40),done=take(sched.reactionAt);
  ProductionScene._bob=12;
  ProductionScene.paint('hamster_idle_base');
  ProductionScene.paint('hamster_idle_01');
  const idleY=BEANSTER_ASSETS.scene.idle.position[1];
  ProductionScene.sprite=orig;
  ProductionScene.spriteBox=origBox;
  ProductionScene.rest();
  const box=ids=>ids.some(id=>String(id).startsWith('box_'));
  return {idleY,ys,bob:ProductionScene._bob,idleBox:box(idle),lookBox:box(look),openBox:box(opening),doneBox:box(done),ivy:idle.includes('ivy_hanging'),board:idle.includes('chalkboard'),sign:idle.includes('entrance_normal'),room:idle.includes('scene_room_day')||idle.includes('scene_room_night')};
});
assert.equal(layers.idleBox,false);
assert.equal(layers.lookBox,false);
assert.equal(layers.openBox,true);
assert.equal(layers.doneBox,false);
assert.equal(layers.ivy,false);
assert.equal(layers.board,false);
assert.equal(layers.sign,true);
assert.equal(layers.room,true);
assert.equal(layers.bob,0);
assert.ok(layers.ys.length>=2);
assert.ok(layers.ys.every(y=>y===layers.idleY),String(layers.ys));
checks.push('idle anchor stays fixed, box only during the open ritual, baked room is not drawn twice');

await page.locator('.cc-room-sign').click();
await page.waitForFunction(()=>document.body.dataset.page==='collection');
assert.equal(await page.locator('#collection h1').innerText(),'咖啡收藏室');
await page.evaluate(()=>UI.go('today'));
checks.push('wooden-sign hotspot opens the collection room');

await page.evaluate(()=>{records=[{id:'dash',ts:Date.now(),caffeine:100,type:'拿铁',productName:'拿铁'}];settings.dailyLimit=400;settings.coffeeDesk={day:CoffeeRoom.today(),ids:['dash']}});
assert.equal(await page.evaluate(()=>Dashboard.companionId(15)),'character_coffee');
await page.evaluate(()=>{records[0].caffeine=319});
assert.equal(await page.evaluate(()=>Dashboard.companionId(15)),'character_coffee');
await page.evaluate(()=>{records[0].caffeine=320});
assert.equal(await page.evaluate(()=>Dashboard.companionId(15)),'character_idle');
await page.evaluate(()=>{records[0].caffeine=400});
assert.equal(await page.evaluate(()=>Dashboard.companionId(15)),'character_late_night');
await page.evaluate(()=>{records[0].caffeine=120});
assert.equal(await page.evaluate(()=>Dashboard.companionId(23)),'character_idle');
await page.evaluate(()=>{records=[]});
assert.equal(await page.evaluate(()=>Dashboard.companionId(15)),'character_wave');
await page.evaluate(()=>{records=[{id:'dash',ts:Date.now(),caffeine:320,type:'拿铁',productName:'拿铁'}];settings.coffeeDesk={day:CoffeeRoom.today(),ids:['dash']};UI.go('dashboard')});
await page.waitForFunction(()=>document.querySelector('#dashboard .u-dash-mascot')?.dataset.motion==='character_idle');
checks.push('dashboard 80% is a quiet reminder and 100% is the late-night caution');

fs.mkdirSync(path.resolve(__dirname,'../qa/v1951'),{recursive:true});
await page.setViewportSize({width:390,height:844});
await page.evaluate(()=>UI.go('today'));
await page.waitForTimeout(200);
await page.locator('.cc-corner').screenshot({path:path.resolve(__dirname,'../qa/v1951/home.png')});
await page.setViewportSize({width:320,height:740});
await page.locator('.cc-corner').screenshot({path:path.resolve(__dirname,'../qa/v1951/home-320.png')});
await page.setViewportSize({width:390,height:844});
await page.evaluate(()=>{ProductionScene.night=()=>true;ProductionScene.sleepy=()=>false;ProductionScene.rest()});
await page.waitForTimeout(150);
await page.locator('.cc-corner').screenshot({path:path.resolve(__dirname,'../qa/v1951/home-night.png')});
const nightLayers=await page.evaluate(()=>{const drawn=[];const orig=ProductionScene.sprite,origBox=ProductionScene.spriteBox;ProductionScene.sprite=function(ctx,id,x,y,scale,alpha){drawn.push(id);return orig.call(this,ctx,id,x,y,scale,alpha)};ProductionScene.spriteBox=function(ctx,id){drawn.push(id);return origBox.call(this,ctx,id)};ProductionScene.paint();ProductionScene.sprite=orig;ProductionScene.spriteBox=origBox;return {ivy:drawn.includes('ivy_hanging'),board:drawn.includes('chalkboard'),room:drawn.includes('scene_room_night'),box:drawn.some(id=>String(id).startsWith('box_'))}});
assert.equal(nightLayers.room,true);
assert.equal(nightLayers.ivy,false);
assert.equal(nightLayers.board,false);
assert.equal(nightLayers.box,false);
await page.evaluate(()=>{ProductionScene.night=function(){const h=new Date().getHours();return h<6||h>=20};ProductionScene.sleepy=function(){const h=new Date().getHours();return h<6||h>=22};ProductionScene.rest()});
await page.evaluate(()=>UI.go('dashboard'));
await page.locator('#dashboard').screenshot({path:path.resolve(__dirname,'../qa/v1951/dashboard.png')});
for(const width of [320,390,480]){await page.setViewportSize({width,height:844});await page.evaluate(()=>UI.go('today'));assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),String(width))}
assert.deepEqual(errors,[]);
fs.writeFileSync(path.resolve(__dirname,'../qa/v1951/results.json'),JSON.stringify({passed:true,checks},null,2));
console.log('PASS '+checks.length+' V19.5.1 visual groups');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
