const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const http=require('node:http');
const {chromium}=require(process.env.BEANSTER_PLAYWRIGHT||'C:/Users/HP/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const ROOT=path.resolve(__dirname,'..'),OUT=path.join(ROOT,'qa','v18');fs.mkdirSync(OUT,{recursive:true});
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.png':'image/png','.webp':'image/webp'};
const server=http.createServer((req,res)=>{const file=path.resolve(ROOT,'.'+decodeURIComponent(req.url.split('?')[0]==='/'?'/index_v5.html':req.url.split('?')[0]));if(!file.startsWith(ROOT+path.sep)){res.writeHead(403);res.end();return}fs.readFile(file,(err,data)=>{if(err){res.writeHead(404);res.end();return}res.setHeader('Content-Type',mime[path.extname(file)]||'application/octet-stream');res.end(data)})});
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});
 try{
  const context=await browser.newContext({viewport:{width:390,height:844},timezoneId:'Asia/Shanghai'});
  const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
  const capture=page.screenshot.bind(page);
  page.screenshot=async options=>capture({...options,style:'#alert,.undo-bar {visibility:hidden!important}'});
  page.on('dialog',async d=>{if(d.type()==='confirm')await d.accept();else await d.dismiss()});
  await page.goto(`http://127.0.0.1:${server.address().port}/`);
  await page.waitForFunction(()=>typeof UI!=='undefined'&&document.querySelector('.u-gauge'));
  await page.evaluate(()=>{settings.systemNotifications=false;persist()});
  await page.screenshot({path:path.join(OUT,'home-empty.png')});
  assert.equal(await page.locator('.u-gauge-copy strong').textContent(),'0');
  await page.evaluate(()=>UI.achievements());
  assert.equal(await page.locator('.u-badge.unlocked').count(),0);
  await page.evaluate(()=>UI.closeOverlay('uAchievements'));
  await page.evaluate(()=>{
    const today=new Date(),day=today.getDate(),types=['美式','拿铁','冷萃','生椰拿铁','手冲'];
    records=Array.from({length:12},(_,i)=>{const d=new Date(today.getFullYear(),today.getMonth(),Math.max(1,day-1-Math.floor(i/2)),9+(i%3)*3,12);return {id:'fixture-'+i,ts:d.getTime(),type:types[i%5],productName:'',caffeine:120+i*5,calories:i%2?180:10,price:18+i,size:350,brand:['星巴克','瑞幸咖啡','Manner'][i%3],temp:'热',rating:4,note:'测试记录',photoId:'',photoPreview:'',nativePhotoPath:'',sourceId:''}});
    const now=new Date(today);now.setHours(9,12,0,0);records.push({id:'fixture-today',ts:now.getTime(),type:'美式',caffeine:160,calories:10,price:8,size:350,brand:'星巴克',temp:'热',note:'',photoId:'',photoPreview:'',sourceId:''});
    settings.dailyLimit=240;settings.customBrands=[];persist();renderAll();
  });
  await page.screenshot({path:path.join(OUT,'home.png')});
  assert.equal(await page.locator('.u-gauge-copy strong').textContent(),'160');
  await page.locator('.u-record-cta').click();
  await page.locator('#uDrinkChoices .u-choice').first().click();
  await page.locator('#uBrandChoices .u-choice').first().click();
  await page.screenshot({path:path.join(OUT,'record.png')});
  assert.equal(await page.locator('#fType').inputValue(),'拿铁');
  await page.locator('#uCupChoices .u-choice').nth(2).click();assert.equal(await page.locator('#fSize').inputValue(),'450');
  await page.locator('#uBrandChoices .u-choice').last().click();
  await page.screenshot({path:path.join(OUT,'brands.png')});
  await page.locator('#uNewBrand').fill('测试咖啡馆');await page.locator('.u-custom-brand button').click();
  assert.equal(await page.locator('#fBrand').inputValue(),'测试咖啡馆');
  await page.locator('#fCaf').fill('70');await page.locator('#fPrice').fill('22.5');await page.locator('#fProductName').fill('桂花拿铁');await page.locator('#fNote').fill('少糖');
  await page.locator('#uSave').click();await page.waitForFunction(()=>!document.querySelector('#addModal').classList.contains('show'));
  assert.equal(await page.evaluate(()=>records.length),14);
  assert.equal(await page.evaluate(()=>records.find(r=>r.productName==='桂花拿铁').brand),'测试咖啡馆');
  assert.equal(await page.evaluate(()=>sum(dayRecords(),'caffeine')),230);
  const newId=await page.evaluate(()=>records.find(r=>r.productName==='桂花拿铁').id);
  await page.evaluate(id=>editRecord(id),newId);
  assert.equal(await page.locator('#fNote').inputValue(),'少糖');
  await page.locator('#fPrice').fill('25');await page.locator('#uSave').click();
  await page.waitForFunction(()=>!document.querySelector('#addModal').classList.contains('show'));
  assert.equal(await page.evaluate(id=>records.find(r=>r.id===id).price,newId),25);
  await page.evaluate(id=>delRecord(id),newId);
  assert.equal(await page.evaluate(()=>records.length),13);
  await page.evaluate(()=>undoLastChange());assert.equal(await page.evaluate(()=>records.length),14);
  await page.reload();await page.waitForFunction(()=>typeof UI!=='undefined'&&document.querySelector('.u-gauge'));
  assert.equal(await page.evaluate(()=>records.length),14);
  assert.ok(await page.evaluate(()=>settings.customBrands.includes('测试咖啡馆')));
  await page.locator('.nav [data-page="analysis"]').click();await page.screenshot({path:path.join(OUT,'monthly.png')});
  assert.equal(await page.locator('.u-month-stats>div').first().locator('b').textContent(),'14');
  await page.locator('.u-report-tabs button').nth(1).click();await page.screenshot({path:path.join(OUT,'categories.png')});
  await page.locator('.u-report-tabs button').nth(3).click();await page.screenshot({path:path.join(OUT,'insights.png')});
  await page.locator('.u-report-tabs button').first().click();
  await page.locator('.u-calendar-day.is-today').click();await page.screenshot({path:path.join(OUT,'calendar-detail.png')});
  await page.locator('#uDayNote').fill('今天风味很好');await page.locator('.u-day-note button').click();
  assert.equal(await page.evaluate(()=>settings.dayNotes[UI.dayKey]),'今天风味很好');
  await page.evaluate(()=>UI.shiftDay(-1));const selected=await page.evaluate(()=>UI.dayKey);
  await page.locator('.u-day-add').click();assert.equal(await page.locator('#fDate').inputValue(),selected);
  await page.keyboard.press('Escape');assert.equal(await page.locator('#addModal').evaluate(e=>e.classList.contains('show')),false);assert.equal(await page.locator('#uDay').count(),1);
  await page.locator('.u-day-add').click();
  await page.locator('#fCaf').fill('30');await page.locator('#uSave').click();await page.waitForFunction(()=>!document.querySelector('#addModal').classList.contains('show'));
  assert.equal(await page.evaluate(()=>localKey(new Date(records.at(-1).ts))),selected);
  await page.evaluate(()=>UI.closeOverlay('uDay'));await page.evaluate(()=>UI.achievements());
  await page.screenshot({path:path.join(OUT,'achievements.png')});assert.equal(await page.locator('.u-badge').count(),24);assert.ok(await page.locator('.u-badge.unlocked').count()>0);
  await page.evaluate(()=>UI.closeOverlay('uAchievements'));
  await page.evaluate(async()=>{const r=records.find(r=>r.id==='fixture-today'),c=document.createElement('canvas');c.width=8;c.height=8;c.getContext('2d').fillRect(0,0,8,8);const image=c.toDataURL();await putPhoto('fixture-today',{full:image,display:image,thumb:image});await putPhoto('fixture-source',{full:image});r.photoId='fixture-today';r.sourceId='fixture-source';r.sourceMime='image/png';r.photoPreview=image;r.infoSourceKind='label';persist();});
  await page.evaluate(()=>editRecord('fixture-today'));await page.locator('#fNote').fill('保留照片与杯贴');await page.locator('#uSave').click();await page.waitForFunction(()=>!document.querySelector('#addModal').classList.contains('show'));
  const media=await page.evaluate(async()=>{const r=records.find(r=>r.id==='fixture-today');return {photo:r.photoId,source:r.sourceId,hasOriginal:!!(await getPhoto(r.photoId)).full,hasSource:!!(await getPhoto(r.sourceId)).full}});assert.deepEqual(media,{photo:'fixture-today',source:'fixture-source',hasOriginal:true,hasSource:true});
  await page.evaluate(()=>editRecord('fixture-today'));await page.evaluate(()=>viewInfoSource('fixture-today'));await page.locator('.viewer-toolbar button').first().click();assert.equal(await page.locator('#addModal').evaluate(e=>e.classList.contains('show')),true);await page.evaluate(()=>viewInfoSource('fixture-today'));await page.keyboard.press('Escape');assert.equal(await page.locator('#photoViewer').evaluate(e=>e.classList.contains('show')),false);assert.equal(await page.locator('#addModal').evaluate(e=>e.classList.contains('show')),true);await page.evaluate(()=>closeAdd());
  const assetCheck=await page.evaluate(async()=>{const refs=new Set([...document.images].filter(i=>i.getAttribute('src')).map(i=>i.src));const missing=[];await Promise.all([...refs].filter(Boolean).map(src=>new Promise(resolve=>{const img=new Image();img.onload=resolve;img.onerror=()=>{missing.push(src);resolve()};img.src=src})));return missing});assert.deepEqual(assetCheck,[]);
  await page.evaluate(()=>{window.savedExport=null;exportFile=(data,mime,name)=>{window.savedExport={data,mime,name}};exportBackup()});
  const backup=await page.evaluate(()=>JSON.parse(window.savedExport.data));assert.equal(backup.records.length,15);assert.ok(backup.settings.customBrands.includes('测试咖啡馆'));assert.ok(Object.values(backup.settings.dayNotes).includes('今天风味很好'));
  await page.evaluate(()=>{const before=records.length;pendingImport={obj:{records:records.map(r=>({...r}))},stats:analyzeImport(records)};window.beforeImport=before});await page.evaluate(()=>applyImport('append'));assert.equal(await page.evaluate(()=>records.length),15);
  await page.setViewportSize({width:320,height:740});await page.locator('.nav [data-page="today"]').click();await page.screenshot({path:path.join(OUT,'home-320.png')});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await page.evaluate(()=>openAdd());assert.equal(await page.evaluate(()=>document.querySelector('.u-add-sheet').scrollWidth>innerWidth),false);await page.evaluate(()=>closeAdd());
  await page.emulateMedia({reducedMotion:'reduce'});await page.evaluate(()=>renderAll());assert.ok(await page.locator('.u-home-mascot').getAttribute('src').then(s=>s.endsWith('.png')));
  assert.deepEqual(errors,[]);
  const checks=['empty state','live gauge','type/brand/size selectors','custom brand persistence','record create/edit/delete/undo','reload persistence','monthly totals and tabs','day navigation and notes','backdated record','24 real achievements','runtime asset loading','backup data preservation','duplicate import','320px layout','reduced motion','nested dialog Escape','photo and source attachment preservation'];
  fs.writeFileSync(path.join(OUT,'test-results.json'),JSON.stringify({passed:true,checks,pageErrors:errors},null,2));
  console.log(`PASS: UI functional regression suite, ${checks.length} checks.`);
 }finally{await browser.close();await new Promise(r=>server.close(r))}
})().catch(e=>{console.error(e);server.close();process.exitCode=1});
