// Native transport contract with real desktop inference, NOT Android acceptance.
const fs=require('fs'),path=require('path'),{spawn}=require('child_process'),readline=require('readline'),assert=require('assert/strict');
const {chromium}=require('C:/Users/HP/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..'),out=path.join(root,'qa/private');fs.mkdirSync(out,{recursive:true});
(async()=>{const worker=spawn('D:/anaconda/python.exe',[path.join(root,'tools/desktop_vision.py'),'--server'],{stdio:['pipe','pipe','ignore']});const lines=readline.createInterface({input:worker.stdout});await new Promise((resolve,reject)=>{const t=setTimeout(()=>reject(Error('Desktop runtime startup timeout')),45000);lines.once('line',line=>{clearTimeout(t);assert.equal(JSON.parse(line).ready,true);resolve()});worker.once('error',reject)});const b=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});try{const p=await b.newPage();
await p.exposeFunction('classifyPixels',base64=>new Promise((resolve,reject)=>{const f=path.join(out,'vision.rgb'),bytes=Buffer.from(base64,'base64');assert.equal(bytes.length,224*224*3);fs.writeFileSync(f,bytes);lines.once('line',line=>resolve(JSON.parse(line)));worker.stdin.write(JSON.stringify(f)+'\n')}));
await p.goto('file:///'+path.join(root,'index_v5.html').replaceAll('\\','/'));await p.evaluate(()=>{let pixels='',results={};window.prompt=url=>{const u=new URL(url);if(u.host==='visioncapabilities')return 'native-vision-1';if(u.host==='visionbegin'){pixels='';return '0'}if(u.host==='visionchunk'){pixels+=atob(u.searchParams.get('data'));return String(pixels.length)}if(u.host==='visionfinish'){const id=u.searchParams.get('meta');results[id]={status:'pending'};window.classifyPixels(btoa(pixels)).then(r=>results[id]=r);return 'pending'}if(u.host==='visionpoll')return JSON.stringify(results[u.searchParams.get('id')]||{status:'missing'});if(u.host==='visioncancel')return 'cancelled';return ''}});
const file=process.argv[2];if(!file)throw Error('Full input image required');const data='data:image/png;base64,'+fs.readFileSync(file).toString('base64');
const result=await p.evaluate(async data=>{const im=new Image();im.src=data;await im.decode();return LocalVision.infer(im)},data);assert.equal(result.status,'done');assert.ok(result.top.length===5);fs.writeFileSync(path.join(out,'vision-desktop.json'),JSON.stringify({scope:'desktop diagnostic, not Android',result},null,2));console.log(JSON.stringify(result));
}finally{await b.close();worker.kill()}})().catch(e=>{console.error(e);process.exitCode=1});
