const assert=require('assert/strict'),path=require('path'),fs=require('fs');
const {chromium}=require('C:/Users/HP/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});try{const p=await b.newPage({viewport:{width:390,height:844},hasTouch:true}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('file:///'+path.resolve(__dirname,'../index_v5.html').replaceAll('\\','/'));
 const swipe=async(dx,dy=0,selector='.page.active')=>{await p.evaluate(({dx,dy,selector})=>{const el=document.querySelector(selector),x=dx>0?60:300,y=300;for(const [type,offset] of [['touchstart',0],['touchmove',.6],['touchend',1]]){const t=new Touch({identifier:1,target:el,clientX:x+dx*offset,clientY:y+dy*offset});el.dispatchEvent(new TouchEvent(type,{bubbles:true,cancelable:true,touches:type==='touchend'?[]:[t],changedTouches:[t]}))}},{dx,dy,selector});await p.waitForTimeout(450)};
 assert.equal(await p.locator('body>.top').isVisible(),false);assert.equal(await p.locator('.cc-dashboard-panel .u-gauge').isVisible(),true);assert.equal(await p.locator('.cc-dashboard-details').count(),0);assert.ok((await p.locator('.cc-corner').boundingBox()).width>=390);assert.ok((await p.locator('.cc-corner').boundingBox()).height>=380);
 for(const direction of [180,180,-180,-180]){const before=await p.evaluate(()=>CoffeePages.current());await swipe(direction);assert.notEqual(await p.evaluate(()=>CoffeePages.current()),before)}assert.equal(await p.evaluate(()=>CoffeePages.current()),'today');
 await swipe(20,180);assert.equal(await p.evaluate(()=>CoffeePages.current()),'today');await swipe(40);assert.equal(await p.evaluate(()=>CoffeePages.current()),'today');
 await p.evaluate(()=>CoffeeRoom.open());await swipe(180,0,'#ccSearch');assert.equal(await p.evaluate(()=>CoffeePages.current()),'collection');
 await p.evaluate(()=>openAdd());await swipe(180,0,'#addModal');assert.equal(await p.locator('#addModal.show').count(),1);assert.equal(await p.evaluate(()=>CoffeePages.current()),'collection');await p.evaluate(()=>AppNav.discard());
 await p.evaluate(()=>{records=[{id:'detail',ts:Date.now(),type:'拿铁',caffeine:160}];CoffeeRoom.detail('detail')});await swipe(180,0,'#ccDetail');assert.equal(await p.locator('#ccDetail').count(),1);await p.evaluate(()=>AppNav.back());assert.equal(await p.locator('#ccDetail').count(),0);assert.equal(await p.evaluate(()=>CoffeePages.current()),'collection');await p.evaluate(()=>AppNav.back());assert.equal(await p.evaluate(()=>CoffeePages.current()),'today');await p.evaluate(()=>AppNav.back());assert.equal(await p.evaluate(()=>CoffeePages.current()),'collection');
 await p.emulateMedia({reducedMotion:'reduce'});await swipe(180);assert.equal(await p.evaluate(()=>CoffeePages.current()),'today');assert.equal(await p.locator('[data-playing]').count(),0);
 for(const width of [320,390,480]){await p.setViewportSize({width,height:844});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.ok(await p.locator('.cc-dashboard-panel .u-gauge').isVisible())}
 assert.deepEqual(errors,[]);fs.mkdirSync('qa/v191',{recursive:true});fs.writeFileSync('qa/v191/swipe-results.json',JSON.stringify({passed:true,checks:['home header removed and gauge visible','full-width larger scene','both directions wrap repeatedly','vertical and short gestures ignored','search and edit gestures ignored','details close before page switching','Android Back cycles root pages','reduced motion','320/390/480 layout']},null,2));console.log('PASS 9 dashboard and circular gesture groups');
 }finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
