const assert=require('assert/strict'),path=require('path'),fs=require('fs');
const {chromium}=require('C:/Users/HP/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});try{const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());await page.goto('file:///'+path.resolve(__dirname,'../index_v5.html').replaceAll('\\','/'));await page.waitForTimeout(80);
 assert.equal(await page.locator('.cc-desk-cup').count(),0);await page.evaluate(()=>CoffeeRoom.open());assert.equal(await page.locator('.cc-room-empty').count(),1);await page.getByRole('button',{name:'＋ 去记录一杯',exact:true}).click();assert.equal(await page.locator('#addModal.show').count(),1);await page.evaluate(()=>AppNav.discard());checks.push('empty desk, empty collection and first-record action');
 // Real save path: same drink on two visits remains two records, backdated save goes only to shelves.
 await page.evaluate(()=>{settings.systemNotifications=false;UI.go('today');openAdd();$('fProductName').value='轻椰茉莉拿铁';UI.chooseBrand('Starbucks');$('fNote').value='今天的第一杯';currentRating=4});await page.evaluate(()=>saveRecord());assert.equal(await page.locator('.cc-desk-cup').count(),1);assert.equal(await page.evaluate(()=>CoffeeRoom.valid().length),1);
 await page.evaluate(()=>{openAdd();$('fProductName').value='轻椰茉莉拿铁'});await page.evaluate(()=>saveRecord());assert.equal(await page.locator('.cc-desk-cup').count(),2);assert.equal(await page.evaluate(()=>new Set(records.map(r=>r.id)).size),2);
 await page.evaluate(()=>{openAdd();const d=new Date();d.setDate(d.getDate()-1);$('fDate').value=localKey(d);$('fProductName').value='补记美式'});await page.evaluate(()=>saveRecord());assert.equal(await page.locator('.cc-desk-cup').count(),2);await page.evaluate(()=>CoffeeRoom.open());assert.equal(await page.locator('.cc-collection-cup').count(),3);checks.push('immediate collection membership, duplicate drinks, yesterday excluded from desk');
 await page.locator('#ccSearch').fill('轻椰');assert.equal(await page.locator('.cc-collection-cup').count(),2);await page.locator('#ccSearch').fill('Starbucks');assert.ok(await page.locator('.cc-collection-cup').count()>=1);await page.locator('#ccSearch').fill('找不到的名字');assert.equal(await page.locator('.cc-no-results').count(),1);await page.evaluate(()=>CoffeeRoom.search(CoffeeRoom.today()));assert.equal(await page.locator('.cc-collection-cup').count(),2);checks.push('search name, brand, date and no-results state');
 const first=await page.evaluate(()=>records.find(r=>r.note==='今天的第一杯').id);await page.evaluate(id=>CoffeeRoom.detail(id),first);assert.ok((await page.locator('#ccDetailContent').innerText()).includes('今天的第一杯'));assert.ok((await page.locator('#ccDetailContent').innerText()).includes('★★★★'));assert.ok((await page.locator('#ccDetailContent').innerText()).includes(String(new Date().getFullYear())));
 await page.getByRole('button',{name:'编辑这杯',exact:true}).click();await page.locator('#fProductName').fill('更新后的拿铁');await page.evaluate(()=>{const d=new Date();d.setDate(d.getDate()-2);$('fDate').value=localKey(d)});await page.evaluate(()=>saveRecord());assert.ok((await page.locator('#ccDetailContent h1').innerText()).includes('更新后的拿铁'));assert.equal(await page.locator('.cc-desk-cup').count(),1);await page.getByRole('button',{name:'删除',exact:true}).click();assert.equal(await page.locator('#ccDetail').count(),0);assert.equal(await page.evaluate(id=>records.some(r=>r.id===id),first),false);await page.evaluate(()=>undoLastChange());assert.equal(await page.evaluate(id=>records.some(r=>r.id===id),first),true);checks.push('detail fields, edit date synchronization, delete and undo');
 await page.evaluate(()=>{UI.go('today');for(let i=0;i<5;i++)records.push({id:'many-'+i,ts:Date.now()-i*1000,type:'冷萃',caffeine:5,productName:'冷萃 '+i});persist();renderAll()});assert.equal(await page.locator('.cc-desk-cup').count(),4);await page.locator('.cc-more').click();assert.equal(await page.locator('.cc-collection-cup').count(),6);await page.locator('.cc-collection-cup').first().click();assert.equal(await page.evaluate(()=>AppNav.back()),true);assert.equal(await page.locator('#collection.active').count(),1);assert.equal(await page.evaluate(()=>AppNav.back()),true);assert.equal(await page.locator('#today.active').count(),1);checks.push('4-cup cap, more entry and detail-to-room-to-home back navigation');
 const transition=await page.evaluate(()=>{const today=CoffeeRoom.today(),d=new Date();d.setDate(d.getDate()-5);const old={id:'old-desk',ts:d.getTime(),type:'美式'},backdated={id:'backdated',ts:d.getTime(),type:'拿铁'},fresh={id:'fresh',ts:Date.now(),type:'拿铁'},state={day:CoffeeRoom.day(d.getTime()),ids:['old-desk']};const first=CoffeeRoom.transition(state,today,[old,backdated,fresh]);return {old:first.old.map(r=>r.id),next:first.next.ids,again:CoffeeRoom.transition(first.next,today,[old,backdated,fresh]).old.length}});assert.deepEqual(transition,{old:['old-desk'],next:['fresh'],again:0});checks.push('missed days collapse to one ritual; only previous visible cups move');
 await page.evaluate(()=>{const d=new Date();d.setDate(d.getDate()-3);records=[{id:'old-desk',ts:d.getTime(),type:'美式'},{id:'fresh',ts:Date.now(),type:'拿铁'}];settings.coffeeDesk={day:CoffeeRoom.day(d.getTime()),ids:['old-desk']};renderAll()});await page.waitForTimeout(80);assert.equal(await page.locator('.cc-ritual').count(),1);assert.equal(await page.locator('.cc-desk-cup[data-record-id="fresh"]').count(),1);assert.deepEqual(await page.evaluate(()=>CoffeeRoom.ritual.map(r=>r.id)),['old-desk']);assert.ok(await page.locator('[data-playing]').count()<=1);await page.getByRole('button',{name:'跳过',exact:true}).click();assert.equal(await page.locator('.cc-ritual').count(),0);await page.reload();await page.waitForTimeout(80);assert.equal(await page.locator('.cc-ritual').count(),0);assert.equal(await page.evaluate(()=>records.length),2);checks.push('actual once-only 1.8s ritual, skip and restart preserve today and records');
 await page.evaluate(()=>{const d=new Date();d.setDate(d.getDate()-1);settings.coffeeDesk={day:CoffeeRoom.day(d.getTime()),ids:['old-desk']};renderToday()});await page.waitForTimeout(80);assert.equal(await page.locator('.cc-ritual').count(),1);await page.waitForTimeout(1900);assert.equal(await page.locator('.cc-ritual').count(),0);assert.equal(await page.evaluate(()=>records.length),2);checks.push('natural ritual completion does not mutate records');
 await page.emulateMedia({reducedMotion:'reduce'});await page.evaluate(()=>{const d=new Date();d.setDate(d.getDate()-1);settings.coffeeDesk={day:CoffeeRoom.day(d.getTime()),ids:['old-desk']};renderToday()});await page.waitForTimeout(50);assert.equal(await page.locator('.cc-ritual').count(),0);checks.push('reduced motion consumes ritual without animation');
 // Asset alpha is real; all nine cells contain art. Loading errors must not become invisible broken images.
 const alpha=await page.evaluate(async(src)=>{const im=new Image();im.src=src;await im.decode();const c=document.createElement('canvas');c.width=im.width;c.height=im.height;const ctx=c.getContext('2d');ctx.drawImage(im,0,0);const data=ctx.getImageData(0,0,c.width,c.height).data;let transparent=0;for(let i=3;i<data.length;i+=4)if(data[i]===0)transparent++;return transparent/(c.width*c.height)},'data:image/png;base64,'+fs.readFileSync('art/coffee-room/drinks.png').toString('base64'));assert.ok(alpha>.1);
 for(const width of [320,390,480]){await page.setViewportSize({width,height:844});await page.evaluate(()=>CoffeeRoom.open());assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(await page.evaluate(()=>[...document.querySelectorAll('#collection img')].filter(im=>!im.complete||im.naturalWidth===0).map(im=>im.src)),[])}checks.push('transparent drink atlas and 320/390/480px layout');
 await page.evaluate(async()=>{const c=document.createElement('canvas');c.width=30;c.height=30;c.getContext('2d').fillRect(0,0,30,30);const raw=c.toDataURL();await putPhoto('fresh',{full:raw,preview:raw,thumb:raw});const r=records.find(r=>r.id==='fresh');r.photoId='fresh';r.photoPreview=raw;r.productName='<img src=x onerror=alert(1)>';persist();CoffeeRoom.detail('fresh')});await page.waitForTimeout(50);assert.equal(await page.locator('.cc-detail-photo img').evaluate(im=>im.naturalWidth),30);assert.equal(await page.locator('.cc-detail-hero h1').innerText(),'<img src=x onerror=alert(1)>');await page.evaluate(()=>AppNav.back());checks.push('photo hydration and escaped user content in detail');
 await page.evaluate(()=>{records=Array.from({length:125},(_,i)=>({id:'page-'+i,ts:Date.now()-i*60000,type:'拿铁',productName:'同款咖啡'}));CoffeeRoom.open()});assert.equal(await page.locator('.cc-collection-cup').count(),60);await page.locator('.cc-load-more').click();assert.equal(await page.locator('.cc-collection-cup').count(),120);await page.locator('.cc-load-more').click();assert.equal(await page.locator('.cc-collection-cup').count(),125);assert.equal(await page.locator('.cc-load-more').count(),0);checks.push('all records reachable through shelf pagination without drink deduplication');
 assert.deepEqual(errors,[]);fs.mkdirSync('qa/v190',{recursive:true});fs.writeFileSync('qa/v190/results.json',JSON.stringify({passed:true,checks},null,2));console.log('PASS '+checks.length+' coffee room integration groups');
 }finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
