const assert=require('assert/strict'),path=require('path'),fs=require('fs');const {chromium}=require('C:/Users/HP/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});try{const p=await b.newPage({viewport:{width:390,height:844}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('file:///'+path.resolve(__dirname,'../index_v5.html').replaceAll('\\','/'));
await p.waitForFunction(()=>window.BEANSTER_ASSETS&&document.querySelector('[data-scene]'));
await p.waitForFunction(()=>document.querySelector('[data-scene][data-playing],[data-scene]:not([data-playing])'));
await p.waitForTimeout(2500);assert.equal(await p.locator('[data-playing]').count(),0);
await p.locator('[data-scene]').click();await p.waitForFunction(()=>document.querySelector('[data-scene]').dataset.expression);const sample=await p.evaluate(async()=>{const canvas=document.querySelector('[data-scene]'),frames=new Set();const start=performance.now();while(performance.now()-start<2200){frames.add(canvas.dataset.frame);if(document.querySelectorAll('[data-playing]').length>1)throw Error('multiple animations');await new Promise(r=>setTimeout(r,40))}return {frames:[...frames],kind:canvas.dataset.expression}});assert.ok(sample.frames.length>=3,sample.kind);assert.ok(['idle','sleep'].includes(sample.kind));
await p.evaluate(()=>{ProductionScene.play('toast'.replace('toast','idle'),id=>ProductionScene.paint(id));showIdleSaveSticker(1,false)});await p.waitForTimeout(80);assert.ok(await p.locator('[data-playing]').count()<=1);
await p.evaluate(()=>{settings.dashboardStyle='cup';records=[{id:'motion',ts:Date.now(),type:'拿铁',caffeine:160}];UI.go('dashboard')});await p.locator('[data-dashboard]').click();assert.equal(await p.locator('.u-pouring').count(),1);await p.evaluate(()=>UI.go('today'));await p.locator('[data-scene]').click();assert.equal(await p.locator('.u-pouring').count(),0);
await p.emulateMedia({reducedMotion:'reduce'});await p.locator('[data-scene]').click();assert.equal(await p.locator('[data-playing]').count(),0);
for(const width of [320,390,480]){await p.setViewportSize({width,height:844});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),String(width))}
assert.ok(await p.evaluate(()=>BEANSTER_ASSETS.animations.sleep.frames.length>=6));assert.ok(await p.evaluate(()=>BEANSTER_ASSETS.animations.clap.frames.length>=6));assert.ok(await p.evaluate(()=>BEANSTER_ASSETS.assets.paw_front));
assert.deepEqual(errors,[]);fs.mkdirSync('qa/v193',{recursive:true});console.log('PASS production scene entry, click idle/sleep, arbitration, reduced motion, layout and P1 animations');
}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
