const assert=require('assert/strict'),path=require('path'),fs=require('fs');const {chromium}=require('C:/Users/HP/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});try{const p=await b.newPage({viewport:{width:390,height:844}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('file:///'+path.resolve(__dirname,'../index_v5.html').replaceAll('\\','/'));await p.waitForFunction(()=>document.querySelector('[data-seated][data-playing]'));await p.waitForTimeout(1500);assert.equal(await p.locator('[data-playing]').count(),0);await p.waitForTimeout(500);assert.equal(await p.locator('[data-playing]').count(),0);assert.equal(await p.locator('[data-seated]').getAttribute('data-frame'),'0:0');
for(const kind of ['idle','point','toast','wave']){await p.locator('[data-seated]').click();await p.waitForFunction(kind=>document.querySelector('[data-seated]').dataset.expression===kind,kind);const sample=await p.evaluate(async()=>{const canvas=document.querySelector('[data-seated]'),frames=new Set(),boxes=new Set();const start=performance.now();while(performance.now()-start<1900){frames.add(canvas.dataset.frame);const r=canvas.getBoundingClientRect();boxes.add([r.x,r.y,r.width,r.height].join(','));if(document.querySelectorAll('[data-playing]').length>1)throw Error('multiple animations');await new Promise(r=>setTimeout(r,50))}return {frames:[...frames],boxes:boxes.size}});assert.ok(sample.frames.length>=6,kind);assert.equal(sample.boxes,1);assert.equal(await p.locator('[data-playing]').count(),0)}
await p.evaluate(()=>{SeatedMotion.play(document.querySelector('[data-seated]'),'toast');showIdleSaveSticker(1,false)});await p.waitForTimeout(80);assert.equal(await p.locator('[data-seated][data-playing]').count(),0);assert.ok(await p.locator('[data-playing]').count()<=1);
await p.evaluate(()=>{settings.dashboardStyle='cup';records=[{id:'motion',ts:Date.now(),type:'拿铁',caffeine:160}];UI.go('dashboard')});await p.locator('[data-dashboard]').click();assert.equal(await p.locator('.u-pouring').count(),1);await p.evaluate(()=>UI.go('today'));await p.locator('[data-seated]').click();assert.equal(await p.locator('.u-pouring').count(),0);
await p.emulateMedia({reducedMotion:'reduce'});await p.locator('[data-seated]').click();assert.equal(await p.locator('[data-playing]').count(),0);assert.equal(await p.locator('[data-seated]').getAttribute('data-frame'),'0:0');
for(const width of [320,390,480]){await p.setViewportSize({width,height:844});const gap=await p.evaluate(()=>{const c=document.querySelector('[data-seated]').getBoundingClientRect(),t=document.querySelector('.cc-table').getBoundingClientRect();const paws=c.y+c.height*520/560;return paws-t.y});assert.ok(gap>=0&&gap<25,'hands overlap tabletop back edge '+width+': '+gap)}
await p.setViewportSize({width:1100,height:900});await p.evaluate(async()=>{Motion.stop();await SeatedMotion.load();const board=document.createElement('div');board.id='frameQA';board.style.cssText='position:absolute;top:0;left:0;width:1080px;z-index:99999;background:#ead7bb;display:grid;grid-template-columns:repeat(6,180px)';for(let sheet=0;sheet<2;sheet++)for(let i=0;i<(sheet?18:8);i++){const cell=document.createElement('div');const c=document.createElement('canvas');c.width=640;c.height=560;c.style.cssText='width:180px;height:158px';cell.append(c);cell.append(document.createTextNode((sheet?'action':'idle')+' '+i));board.append(cell);document.body.append(board);SeatedMotion.draw(c,sheet,i)}});fs.mkdirSync('qa/v193',{recursive:true});await p.locator('#frameQA').screenshot({path:'qa/v193/frames.png'});assert.deepEqual(errors,[]);console.log('PASS 26 source frames, entry once, click sequences, fixed layout, animation arbitration, reduced motion and table contact');
}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
