const {chromium}=require('C:/Users/HP/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('assert/strict'),path=require('path');
(async()=>{let b=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});try{let p=await b.newPage({viewport:{width:1280,height:1080}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('file:///'+path.resolve(__dirname,'../art/production-v2/preview.html').replaceAll('\\','/'));await p.waitForFunction(()=>window.assetQA?.ready);await p.evaluate(()=>assetQA.stop());
for(let n of [0,1,4,7]){await p.locator(`[data-count="${n}"]`).click();assert.equal(await p.evaluate(()=>assetQA.desk().length),n);await p.locator('#scene').screenshot({path:path.resolve(__dirname,`../art/production-v2/qa/scene-${n}.png`)});}
await p.locator('#night').click();await p.locator('#scene').screenshot({path:path.resolve(__dirname,'../art/production-v2/qa/scene-night.png')});
await p.locator('#collect').click();await p.waitForTimeout(500);assert.equal(await p.evaluate(()=>assetQA.desk().length),1);assert.equal(await p.evaluate(()=>assetQA.records().length),8);assert.equal(await p.evaluate(()=>assetQA.consumed()),true);assert.ok(await p.evaluate(()=>['cleanup','ending'].includes(assetQA.interaction())));await p.locator('#scene').click();assert.ok(await p.evaluate(()=>['cleanup','ending'].includes(assetQA.interaction())||assetQA.consumed()));await p.locator('#skip').click();assert.equal(await p.evaluate(()=>assetQA.records().length),8);assert.equal(await p.evaluate(()=>assetQA.desk().length),1);assert.equal(await p.evaluate(()=>assetQA.interaction()),'idle');
await p.locator('#reset').click();await p.locator('[data-count="0"]').click();await p.locator('#collect').click();await p.waitForTimeout(180);assert.equal(await p.evaluate(()=>assetQA.desk().length),0);assert.equal(await p.evaluate(()=>assetQA.interaction()),'cleanup');await p.locator('#skip').click();assert.equal(await p.evaluate(()=>assetQA.interaction()),'idle');assert.equal(await p.evaluate(()=>assetQA.consumed()),true);
await p.locator('#play').click();await p.waitForTimeout(1700);await p.emulateMedia({reducedMotion:'reduce'});await p.locator('#play').click();assert.equal(await p.evaluate(()=>assetQA.playing()),false);
await p.setViewportSize({width:390,height:844});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=390));await p.locator('#scene').screenshot({path:path.resolve(__dirname,'../art/production-v2/qa/mobile.png')});assert.deepEqual(errors,[]);console.log('PASS assets load, 0/1/4/7 records, immediate collection, yesterday-only cleanup, skip preserves today/data, reduced motion, 390px layout and no runtime errors');}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
