const assert=require('assert/strict'),fs=require('fs'),path=require('path');
const {chromium}=require('C:/Users/HP/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const ROOT=path.resolve(__dirname,'..'),OUT=path.join(ROOT,'qa/v181');fs.mkdirSync(OUT,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});
try{const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.dismiss());
const capture=page.screenshot.bind(page);page.screenshot=options=>capture({...options,style:'#alert,.undo-bar{visibility:hidden!important}'});
await page.goto('file:///'+path.join(ROOT,'index_v5.html').replaceAll('\\','/'));
await page.waitForFunction(()=>document.querySelectorAll('[data-playing]').length===1);
await page.waitForTimeout(2200);assert.equal(await page.locator('[data-playing]').count(),0);await page.waitForTimeout(1800);assert.equal(await page.locator('[data-playing]').count(),0);checks.push('entry animation plays once');
await page.locator('.u-home-mascot').click();await page.waitForFunction(()=>document.querySelectorAll('[data-playing]').length===1);await page.waitForTimeout(2200);assert.equal(await page.locator('[data-playing]').count(),0);
assert.ok((await page.locator('.u-home-mascot').boundingBox()).width<=118);checks.push('smaller mascot and click replay');
await page.evaluate(()=>Motion.gallery());assert.equal(await page.locator('.u-expression-grid article').count(),14);
await page.locator('.u-expression-grid [data-motion]').nth(1).click();await page.locator('.u-expression-grid [data-motion]').nth(2).click();assert.ok(await page.locator('[data-playing]').count()<=1);checks.push('all 14 expressions exposed; global single player');
await page.screenshot({path:path.join(OUT,'expressions.png')});await page.evaluate(()=>Motion.choose('character_wave'));assert.equal(await page.locator('.u-home-mascot').getAttribute('data-motion'),'character_wave');checks.push('home character preference');
await page.emulateMedia({reducedMotion:'reduce'});await page.locator('.u-home-mascot').click();assert.equal(await page.locator('[data-playing]').count(),0);checks.push('reduced motion honored');
const parsing=await page.evaluate(()=>{
 const positive=['埃塞瑰夏拿铁(杯)','瑞幸咖啡\n生椰拿铁\n少冰','订单详情\n实付 19.9\n澳白','冰美式','Dirty','燕麦拿铁','香草拿铁','摩卡','卡布奇诺','冷萃','手冲','加浓美式','低因咖啡','桂花米酿拿铁','拿铁\n大杯 450ml','Manner\n拿铁'];
 const negative=['机械键盘','人像照片','山川风景','手机壳','卡布奇诺蛋糕','拿铁饼干','咖啡杯','咖啡机','咖啡豆','细吸管','不额外加糖','TEL: 15203880541','付款成功\n订单号169','配件 Z','普通电脑屏幕','牛肉汉堡'];
 return {positive:positive.map(t=>[t,parseOrderText(t).productName]),negative:negative.map(t=>[t,parseOrderText(t).productName])};});
for(const [text,name] of parsing.positive)assert.ok(name,text);for(const [text,name] of parsing.negative)assert.equal(name,'',text);checks.push('32 text cases including non-coffee negatives');
const media=await page.evaluate(async()=>{const c=document.createElement('canvas');c.width=600;c.height=900;c.getContext('2d').fillRect(0,0,600,900);const data=c.toDataURL('image/png');
 records=[{id:'local',ts:Date.now(),updatedAt:200,productName:'新名称',type:'拿铁',brand:'测试',size:350,caffeine:123,price:20}];
 const old={...records[0],updatedAt:100,productName:'旧名称',price:10};readMemory={local:'本地纠错'};
 const pack={records:[old,{...old,id:'separate'}],readMemory:{local:'旧纠错',imported:'导入纠错'},photos:{local:{data,quality:'original'}},sources:{local:{data}}};
 pendingImport={obj:pack,stats:analyzeImport(pack.records)};await applyImport('merge');
 const r=records.find(r=>r.id==='local'),p=await getPhoto('local'),source=await getPhoto('local:source');
 return {n:records.length,name:r.productName,price:r.price,full:photoLegacyFull(p)===data,source:photoLegacyFull(source)===data,memory:JSON.parse(localStorage.getItem(READMEMKEY))};});
assert.equal(media.n,2);assert.equal(media.name,'新名称');assert.equal(media.price,20);assert.equal(media.full,true);assert.equal(media.source,true);assert.deepEqual(media.memory,{local:'本地纠错',imported:'导入纠错'});checks.push('old backups preserve local edits and distinct IDs; original photos, attachments and corrections restored');
const estimated=await page.evaluate(()=>{records=[];const a=estimateFor('拿铁',350,'瑞幸咖啡',1),b=estimateFor('拿铁',350,'瑞幸咖啡',2),c=estimateFor('拿铁',600,'瑞幸咖啡',1);return {a,b,c}});
assert.equal(estimated.b.caf,estimated.a.caf*2);assert.equal(estimated.c.caf,estimated.a.caf);checks.push('shot count respected independent of milk volume and brand');
// Order preprocessing must preserve its middle band.
const middle=await page.evaluate(async()=>{const c=document.createElement('canvas');c.width=300;c.height=1000;const x=c.getContext('2d');x.fillStyle='white';x.fillRect(0,0,300,1000);x.fillStyle='#ff0000';x.fillRect(0,460,300,100);const im=new Image();im.src=c.toDataURL();await im.decode();const blob=await prepareSmartOcrImage(null,'document',im);const out=await createImageBitmap(blob);const dest=document.createElement('canvas');dest.width=out.width;dest.height=out.height;dest.getContext('2d').drawImage(out,0,0);const p=dest.getContext('2d').getImageData(out.width/2,out.height/2,1,1).data;return Array.from(p)});
assert.ok(middle[0]>240&&middle[1]<10);checks.push('entire order including middle preserved');
const stale=await page.evaluate(async()=>{openAdd();const previous=nativeRecognizeBlob;nativeRecognizeBlob=async()=>{await Reader.pause(100);return '埃塞瑰夏拿铁'};
 const im=new Image(),fixture=document.createElement('canvas');fixture.width=200;fixture.height=200;im.src=fixture.toDataURL();await im.decode();const name=$('fProductName').value;
 const cancelled=ocrSmartSource(null,'document',im);setTimeout(()=>Reader.cancel(),30);await cancelled;const unchanged=$('fProductName').value===name;
 const edited=ocrSmartSource(null,'document',im);setTimeout(()=>{$('fProductName').value='自己输入的名字'},30);await edited;
 const kept=$('fProductName').value==='自己输入的名字';let count=0;nativeRecognizeBlob=async()=>{count++;return '无关文字'};await ocrSmartSource(null,'document',im);
 nativeRecognizeBlob=previous;if(typeof AppNav!=="undefined")AppNav.discard();else closeAdd();return {unchanged,kept,count};});
assert.deepEqual(stale,{unchanged:true,kept:true,count:2});checks.push('cancelled and stale reads do not overwrite edits; at most two attempts');
const cancelledTransfer=await page.evaluate(async()=>{
 const oldGray=blobToGrayPixels,oldPrompt=window.prompt;let calls=0;
 window.prompt=()=>{calls++;return ''};
 blobToGrayPixels=async()=>{await Reader.pause(40);return {data:new Uint8Array(4),w:2,h:2}};
 try{const pending=nativeRecognizeBlob(new Blob(),6);setTimeout(()=>Reader.cancel(),10);
  let message='';try{await pending}catch(e){message=e.message}return {calls,message};
 }finally{blobToGrayPixels=oldGray;window.prompt=oldPrompt}
});
assert.deepEqual(cancelledTransfer,{calls:0,message:'reader-cancelled'});checks.push('cancel during grayscale conversion never enters native transfer');
const replacement=await page.evaluate(async()=>{settings.systemNotifications=false;settings.photoQuality='original';openAdd();editingId='replace';records=[{id:'replace',ts:Date.now(),type:'拿铁',nativePhotoPath:'/old/photo.img'}];
 const c=document.createElement('canvas');c.width=500;c.height=700;const raw=c.toDataURL('image/png'),im=new Image();im.src=raw;await im.decode();
 draftPhoto=makePhotoVersions(im,{type:'image/png'},raw);draftPhoto._rawOriginal=raw;draftPhoto.nativePath='';
 const previous=nativeRestorePhotoData;nativeRestorePhotoData=()=>'';await saveRecord();nativeRestorePhotoData=previous;
 const r=records.find(r=>r.id==='replace'),media=await getPhoto('replace');return {path:r.nativePhotoPath,full:media.full===raw,edited:r.updatedAt>0};});
assert.deepEqual(replacement,{path:'',full:true,edited:true});checks.push('replacement photo native-save failure preserves new original in IndexedDB, never old path');
await page.evaluate(()=>{settings.homeCharacter='character_burger';records=[];renderAll()});await page.screenshot({path:path.join(OUT,'home.png')});
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(OUT,'test-results.json'),JSON.stringify({passed:true,checks,parsing},null,2));console.log('PASS: '+checks.length+' V18.1 regression groups');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
