const assert=require('assert/strict'),path=require('path'),fs=require('fs');
const {chromium}=require('C:/Users/HP/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});try{const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
await page.goto('file:///'+path.resolve(__dirname,'../index_v5.html').replaceAll('\\','/'));
await page.waitForFunction(()=>window.BEANSTER_ASSETS&&window.ProductionScene);
assert.equal(await page.locator('[data-scene]').count(),1);
assert.equal(await page.evaluate(()=>BEANSTER_ASSETS.status.includes('p1')),true);
assert.ok(await page.evaluate(()=>['sleep','clap','wipe','zzz','condensation','sweat','question'].every(n=>BEANSTER_ASSETS.animations[n])));
await page.waitForFunction(()=>ProductionScene.images.hamster_idle_base&&ProductionScene.images.scene_background);
checks.push('layered production scene and P1 animations are loaded');
await page.evaluate(()=>{settings.systemNotifications=false;openAdd();$('fProductName').value='轻椰茉莉拿铁';UI.chooseBrand('Starbucks')});await page.evaluate(()=>saveRecord());
assert.equal(await page.locator('.cc-desk-cup').count(),1);
assert.equal(await page.evaluate(()=>ProductionScene.cupId(records[0])),'cup_coconut_latte');
await page.evaluate(()=>CoffeeRoom.open());assert.equal(await page.locator('.cc-collection-cup img').count(),1);
assert.match(await page.locator('.cc-collection-cup img').getAttribute('src'),/cup_coconut_latte/);
await page.evaluate(()=>UI.go('today'));
checks.push('desk and collection use independent production cup sprites');
await page.evaluate(()=>{const d=new Date();d.setDate(d.getDate()-1);records=[{id:'old-desk',ts:d.getTime(),type:'美式',productName:'美式'},{id:'fresh',ts:Date.now(),type:'拿铁',productName:'拿铁'}];settings.coffeeDesk={day:CoffeeRoom.day(d.getTime()),ids:['old-desk']};renderAll()});
await page.waitForTimeout(120);assert.equal(await page.locator('.cc-ritual').count(),1);assert.equal(await page.locator('.cc-desk-cup[data-record-id="fresh"]').count(),1);
await page.waitForFunction(()=>document.querySelector('[data-scene]')?.dataset.expression==='cleanup'||document.querySelector('[data-scene]')?.dataset.expression==='clap'||document.querySelector('[data-scene]')?.dataset.expression==='wipe'||!document.querySelector('.cc-ritual'),{timeout:4000});
if(await page.locator('.cc-ritual').count())await page.getByRole('button',{name:'跳过',exact:true}).click();
await page.waitForFunction(()=>!document.querySelector('.cc-ritual'),{timeout:2000});
assert.equal(await page.evaluate(()=>records.length),2);
checks.push('cleanup ritual binds yesterday cups only and skip preserves records');
await page.emulateMedia({reducedMotion:'reduce'});
await page.evaluate(()=>{const d=new Date();d.setDate(d.getDate()-2);settings.coffeeDesk={day:CoffeeRoom.day(d.getTime()),ids:['old-desk']};renderToday()});
await page.waitForTimeout(80);assert.equal(await page.locator('.cc-ritual').count(),0);
checks.push('reduced motion consumes ritual without animation');
await page.emulateMedia({reducedMotion:'no-preference'});
await page.evaluate(()=>{ProductionScene.sleepy=()=>true;ProductionScene.nudge()});
await page.waitForFunction(()=>document.querySelector('[data-scene]')?.dataset.expression==='sleep',{timeout:2000});
assert.ok(await page.evaluate(()=>String(ProductionScene.fx||'').includes('zzz')||document.querySelector('[data-scene]').dataset.expression==='sleep'));
checks.push('night sleep pose plays with Zzz overlay');
await page.evaluate(()=>ProductionScene.play('clap',id=>ProductionScene.paint(id)));
await page.waitForFunction(()=>document.querySelector('[data-scene]')?.dataset.expression==='clap',{timeout:2000});
assert.ok(await page.evaluate(()=>BEANSTER_ASSETS.assets.paw_front.overlay.includes('after attached cup')));
for(const width of [320,390,480]){await page.setViewportSize({width,height:844});await page.evaluate(()=>UI.go('today'));assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth))}
fs.mkdirSync('qa/v194',{recursive:true});
await page.setViewportSize({width:390,height:844});await page.evaluate(()=>UI.go('today'));await page.waitForTimeout(200);
await page.locator('.cc-corner').screenshot({path:'qa/v194/home.png'});
await page.evaluate(()=>CoffeeRoom.open());await page.locator('#collection').screenshot({path:'qa/v194/collection.png'});
assert.deepEqual(errors,[]);fs.writeFileSync('qa/v194/results.json',JSON.stringify({passed:true,checks},null,2));
console.log('PASS '+checks.length+' production integration groups');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
